<?php use Ovos\Terminal\Highlighter; ?>
<?php use Ovos\Terminal; ?>
<?php use Ovos\Terminal\Table; ?>
<?php use Ovos\View\Helper\Messages\Message; ?>

<?php $messages = $this->messages; ?>
<?php $iterator = new CachingIterator(
	new ArrayIterator($messages),
); ?>

<?php if($this->app->isInterfaceHttp()): ?>
	
	<?php if(count($iterator->getInnerIterator())): ?>
		
		<?php $iconMapping = [
			'error' => 'exclamation-circle',
			'warning' => 'exclamation-circle',
			'info' => 'info-circle',
			'success' => 'check-circle',
		]; ?>
		
		<div class="messages" role="status">
			<?php foreach($iterator as $message): ?>
				<?php /** @var Message $message */ ?>
				<div class="message message-<?= $message->getType(); ?>">
					<div class="message-icon icon-<?= $iconMapping[$message->getType()]; ?>"></div>
					<div class="message-body">
						<?php if($title = $message->getTitle()): ?>
							<h3><?= $title; ?></h3>
						<?php endif; ?>
						<?php if($description = $message->getDescription()): ?>
							<?php if($message->isRaw()): ?>
								<?= $description; ?>
							<?php else: ?>
								<p><?= nl2br($description); ?></p>
							<?php endif; ?>
						<?php endif; ?>
					</div>
				</div>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>
	
<?php else: ?>
<?php /* Do not add an indent above as it will be displayed as a leading space before the table */
		$table = new Table;
		$table->setHeaders([
			Highlighter::header('Messages (' . count($iterator->getInnerIterator()) . ')'),
			Highlighter::header('Type'),
		]);
		
		foreach($iterator as $message)
		{
			/** @var Message $message */
			$text = [$message->getDescription()];
			if($title = $message->getTitle())
			{
				array_unshift($text, $title);
			}
			$table->addRow([
				Highlighter::sanitize(wordwrap(implode(PHP_EOL . PHP_EOL, $text), 150, PHP_EOL)),
				Highlighter::messageType(ucfirst($message->getType())),
			]);
			if($iterator->hasNext())
			{
				$table->addRow([PHP_EOL]);
			}
		}
		
		echo PHP_EOL . Terminal::getMessage($table->getTable(), (bool)$this->markup);
	?>
<?php endif; ?>
