<?php if($this->interface === \Ovos\Application::INT_HTTP): ?>
	
	<?php /*
	<?= $this->render('helpers/debug.phtml'); ?>
	*/ ?>
	
	<div class="debug-table debug-queries">
		
		<div class="row">
			<div class="cell header">Queries (<?= count($this->queries); ?>)</div>
			<div class="cell header">Time</div>
			<div class="cell header">Memory</div>
		</div>
		
		<?php foreach($this->queries as $query): ?>
			<div class="row">
				<div class="cell"><?= $query->sql; ?></div>
				<div class="cell"><?= $query->time; ?></div>
				<div class="cell"><?= $query->memory; ?></div>
			</div>
		<?php endforeach; ?>
	</div>
	
<?php else: ?>
	
	<?php
		$table = new Console_Table();
		$table->setHeaders(['Queries (last ' . count($this->queries) . ')', 'Time', 'Memory']);
		
		foreach($this->queries as $query)
		{
			$table->addRow([
				wordwrap($query->sql, 150, PHP_EOL),
				$query->time,
				$query->memory
			]);
			$table->addRow([PHP_EOL]);
		}
		
		echo PHP_EOL . $table->getTable();
	?>
	
<?php endif; ?>
