<?php use Ovos\Stream\Request; ?>

<?php if($this->interface === \Ovos\Application::INT_HTTP): ?>

	<?php /*
	<?= $this->render('helpers/debug.phtml'); ?>
	*/ ?>
	
	<div class="debug-table debug-requests">
		
		<div class="row">
			<div class="cell header">Requests (<?= count($this->requests); ?>)</div>
			<div class="cell header">Time</div>
			<div class="cell header">Memory</div>
		</div>
		
		<?php foreach($this->requests as $request): ?>
			<?php /** @var Request $request */ ?>
			<div class="row">
				<div class="cell"><?= $request->getMethod(); ?> <?= $request->getUrl(); ?><?php /*<?= wordwrap($request->getUrl(), 100, PHP_EOL); ?>*/ ?></div>
				<div class="cell"><?= $request->getMeasurement()->getTotalTime(); ?></div>
				<div class="cell"><?= $request->getMeasurement()->getTotalMemory(); ?></div>
			</div>
		<?php endforeach; ?>
	</div>
	
<?php else: ?>

	<?php
		$table = new Console_Table();
		$table->setHeaders(['Requests ('. count($this->requests) .')', 'Time', 'Memory']);
	
		foreach($this->requests as $request)
		{
			/** @var Request $request */
			$table->addRow([
				$request->getMethod() . ' '. wordwrap($request->getUrl(), 150, PHP_EOL),
				$request->getMeasurement()->getTotalTime(),
				$request->getMeasurement()->getTotalMemory(),
			]);
			$table->addRow([PHP_EOL]);
		}
	
		echo PHP_EOL . $table->getTable();
	?>
	
<?php endif; ?>
